---
title: "Class 13"
author: "Katie Sanuk"
date: "2026-10-07"
output:
  html_document:
    toc: true
    toc_float: true
    number_sections: TRUE
    code_folding: show
    code_download: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Tidying and Having Technically Correct Data from the PlaceCrash Info Site

```{r}
year = 2025

crash_url = paste0('https://www.planecrashinfo.com/', year, '/', year, '.htm')

# the encoding came from chatisa as shown in class 12
crash_page <- rvest::read_html(crash_url, encoding = "ISO-8859-1")

crash_page |> 
  #selector from inspector (kept the last 3 parts of selector)
  #note the output(we also dropped nth child) in tr since we want all rows
  rvest::html_elements("tr > td:nth-child(1) > font") |> 
rvest::html_text2() -> date_col

crash_page |> 
  #repeat for location
  rvest::html_elements("tr > td:nth-child(2) > font") |> 
rvest::html_text2() -> location_operator

crash_page |> 
  #repeat for location
  rvest::html_elements("tr > td:nth-child(3) > font") |> 
rvest::html_text2() -> aircraft_reg

crash_page |> 
  #repeat for location
  rvest::html_elements("tr > td:nth-child(4) > font") |> 
rvest::html_text2() -> fatalities

# note that the number elements in the four vectors is not equal
df = data.frame(
  date_col = date_col, 
  location_operator = location_operator[-1],
  aircraft_reg = aircraft_reg[-1],
  fatalities = fatalities[-1]
)

#make this tidy
df |> 
  tidyr::separate(col = location_operator, into =c("location", "operator"), sep="\n") |> 
  tidyr::separate(col=aircraft_reg, into =c("aircraft", "registration"), sep="\n") |> 
  tidyr::separate(col=fatalities, into=c("air_fatalities", "num_passed", "ground fatalities")) -> tidy_df
```

