---
title: "class08"
author: "Katie Sanuk"
date: "2026-09-21"
output:
  html_document:
    toc: true
    toc_float: true
    number_sections: TRUE
    code_folding: show
    code_download: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
httr2::request("https://data.cincinnati-oh.gov/resource/rvmt-pkmq.json") |>
  httr2::req_url_query("$limit" = 5) |>
  httr2::req_perform() |>
  httr2::resp_body_string() |>
  jsonlite::fromJSON()
```

```{r}
ohio_jobs =
  httr2::request("https://api.stlouisfed.org/fred/series/observations") |>
  httr2::req_url_query(
    series_id = "IHLIDXUSOH",
    api_key = Sys.getenv("FRED_API_KEY"),
    file_type = "json",
    observation_start='2026-09-01'
  ) |>
  # nothing has been sent yet
  httr2::req_perform() |>
  httr2::resp_body_string() |>
  jsonlite::fromJSON()

dplyr::glimpse(ohio_jobs)
ohio_df=ohio_jobs$observations
ohio_df

##another approach to filter dates
ohio_df |> 
  #overwrite the date column and convert to date (from chr)
  dplyr::mutate(date= lubridate::ymd(date)) |> 
  #because it is a date, we can do logical checks on it and keep dates from sep 01, 2026
  dplyr::filter(date>='2026-09-01') -> ohio_df_sep_2026
```

```{r}
httr2::request("https://data.usajobs.gov/api/search") |>
  httr2::req_url_query(Keyword = "Data Analyst", ResultsPerPage = 500) |>
  httr2::req_headers(
    Host = "data.usajobs.gov",
    "User-Agent" = "yourname@miamioh.edu",
    "Authorization-Key" = Sys.getenv("USAJOBS_API_KEY")
  ) |>
  httr2::req_perform() |>
  httr2::resp_body_string() |>
  jsonlite::fromJSON(flatten = TRUE) -> usa_jobs_data

usa_jobs_data = usa_jobs_data$SearchResult$SearchResultItems
jobs_small=usa_jobs_data |> 
  dplyr::select(
    title = MatchedObjectDescriptor.PositionTitle,
    department=MatchedObjectDescriptor.DepartmentName,
    location=MatchedObjectDescriptor.PositionLocationDisplay,
    closes = MatchedObjectDescriptor.ApplicationCloseDate
  )

jobs_small |> #my answer- hard way
  dplyr::select(title) |> 
  dplyr::filter(title == "Data Analyst") -> postings

#easy way -- since we looked for data analyst as a key word
nrow(jobs_small) #data analyst is a keyword

#q2
table(jobs_small$department) |>  sort(decreasing = T)
jobs_small |>  dplyr::count(department) |> 
  dplyr::arrange(dplyr::desc(n)) |>  head(3)

##the harder way without being literal
#jesse -> data analyst or data analytics side by side
index_data_analyst = jobs_small$title |> 
  stringr::str_detect("Data Analy*") #could also do "data analytics|data analyst"
#given that this is a true or false type result
#true will be kept, nothing means keep all columns
count_jesse_standard = jobs_small[index_data_analyst, ]

```

